FROM node:24-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . ./

ARG VITE_BASE_PATH=/chgka/
ENV VITE_BASE_PATH=${VITE_BASE_PATH}
RUN npm run build


FROM nginx:1.28-alpine

COPY production-nginx.conf /etc/nginx/nginx.conf
COPY --from=build --chown=nginx:nginx /app/dist/ /usr/share/nginx/html/chgka/

USER nginx

EXPOSE 8080

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
