FROM node:18-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json .
RUN npm install

COPY . .

# Запускаем Vite в режиме разработки
CMD ["npm", "run", "dev", "--", "--host"]


